
FilePaths:
    Import FC: Regional/SMS West Mining/SMS Event Log/Import/Factory Campaign
    Import Unit Hours: Regional/SMS West Mining/SMS Event Log/Import/Unit Hours
    980E FH: Fort Hills/02. Equipment Files/1. 980E Trucks
    Factory Campaigns: Regional/SMS West Mining/Factory Campaigns
    Availability: Regional/SMS West Mining/Availability/Reports
    RemanDB: /Volumes/Public/Fort McMurray/service/5. Reliability Department/32. Reman/Condition Report Database
    BaseMineCompDB: /Volumes/Public/Fort McMurray/service/5. Reliability Department/37. Analytical Tools/ComponentTracker.accdb

EquipPaths:
    FortHills: Fort Hills/02. Equipment Files
    BaseMine: Fort McMurray/service/2. Customer Equipment Files/1. Suncor
    Elkford: Elkford/Equipment
    RainyRiver: Rainy River/02. Equipment Files
    Bighorn: Acheson/COALSPUR - BIGHORN/02. Equipment Files
    Bighorn_Opps: Acheson/COALSPUR - BIGHORN/02. Equipment Files # TODO remove this
    CoalValley: Acheson/COAL VALLEY/02. Equipment Files
    ConumaCoal: Acheson/Conuma Coal/02. Equipment Files
    GahchoKue: Gahcho Kue/02. Equipment Files
    Shovels63N: Regional/Fort McMurray/BU-145-ShovelTechs/Customer Equipment Files

ModelPaths:
    FortHills:
        980E: 1. 980E Trucks
        930E: 2. 930E Trucks
        HD1500: 3. HD1500
    BaseMine:
        980E: 1. Trucks/2. 980E
        930E: 1. Trucks/1. 930E
        HD1500: 1. Trucks/3. HD1500

Email: jgordon@smsequip.com

color:
    bg:
        maroon: '#9e2121'
        lightred: '#F8696B'
        lightyellow: '#FFFFCC'
        lightgreen: '#99FF99'
        lightorange: '#ffbf7a'
        lightblue: '#CCECFF'
        darkgreen: '#6db56d'
        darkblue: '#6494b0'
        goodgreen: '#C6EFCE'
        good: '#c6e3ef'
        bad: '#FFC7CE'
        greyrow: '#E4E4E4'
        yellowrow: '#ffff64'
        darkyellow: '#cccc4e'
        darkgrey: '#999999'
        navyblue: '#244062'
        skyblue: '#91c3ff'
        orange: '#f08a37'
        bgdark: '#19232d'
        black: 'black'
    text:
        goodgreen: '#006100'
        good: '#003961'
        bad: '#9C0006'
        black: 'black'
        white: 'white'
    thead: '#244062'

MineSite:
    - BaseMine
    - BaseMine_CWC
    - Bighorn
    - CoalValley
    - CWC_Other
    - Elkford
    - FH-Field
    - FortHills
    - FortHills_CWC
    - GahchoKue
    - RainyRiver
    - Shovels-63N
    - ConumaCoal
    - IOC-RioTinto

Lists:
    WarrantyType:
        - 'Yes'
        - 'No'
        - PRP
        - RAMP
        - Service
        - Parts
    WarrantyTypeCummins:
        - WNTY
        - FME
        - LEMS
    EventLogStatus:
        - Complete
        - Monitor
        - Waiting Parts (UP)
        - Waiting Parts (DOWN)
        - Waiting Customer
        - Work In Progress
        - Planned
    WorkOrdersStatus:
        - Open
        - Closed
        - Cancelled
        - Missing Info
        - Planned
    TSIStatus:
        - Open
        - Closed
        - Missing Info
    ComponentCOStatus:
        - 'True'
        - 'False'
    TrueFalse:
        - 'True'
        - 'False'
    EquipClass:
        - Dozer
        - Dragline
        - Drill
        - Excavator
        - Grader
        - Loader
        - Shovel
        - Truck
        - Truck_Electric
        - Truck_Mechanical
    FailureCategory:
        - Assembly Issue
        - Crack
        - Cold
        - Connection Loose
        - Contamination
        - Failed Component
        - Factory Campaign
        - Improper Maintenance
        - Low Oil/ Fuel
        - Low-hour Failure
        - No Faults Active
        - No Issue
        - Normal Service
        - Normal Wear
        - OEM Issue
        - Operations Damage
        - Operator Error
        - Snow/ Ice
        - Vibration
        - Water
        - Calibration
        - Customer Request
    RemovalReason:
        - High Hour Changeout
        - Damage/Abuse
        - Convenience
        - Failure
        - Pro Rata Buy-in
        - Warranty


# Convert title to tablename > can select from views but not update them
TableName:
    Class: # map class name to title
        EventLog: Event Log
        WorkOrders: Work Orders
        TSI: TSI
        ComponentCO: Component CO
        ComponentSMR: Component SMR
        ComponentCOReport: Component CO
        UnitInfo: Unit Info
        NewFCs: FC Summary
        FCSummary: FC Summary
        FCDetails: FC Details
        EmailList: Email List
        Availability: Availability
        OilSamples: Oil Samples
        UserSettings: Users
    Select:
        EventLogBase: EventLog
        FCBase: viewFactoryCampaign
        ComponentSMR: viewPredictedCO
        UnitInfo: UnitID
        EmailList: EmailList
        AvailTopDowns: Downtime
        AvailBase: Downtime
        UserSettings: UserSettings
        OilSamples: viewOilSamples
    Update:
        FCSummary: FCSummary
        FCDetails: FactoryCampaign
        NewFCs: FCSummary # dont actually need this, remove somehow
        UserSettings: UserSettings
        OilSamples: OilSamples

# Table header conversion
Headers:
    Event Log:
        UID: UID
        Passover: PassoverSort
        Status: StatusEvent
        Unit: Unit
        Title: Title
        Description: Description
        Failure Cause: FailureCause
        Date Added: DateAdded
        Date Complete: DateCompleted
        Issue Category: IssueCategory
        Sub Category: SubCategory
        Failure Category: Cause
        Added By: CreatedBy
        Time Called: TimeCalled

    Work Orders:
        UID: UID
        Status: StatusWO
        Wrnty: WarrantyYN
        Work Order: WorkOrder
        Seg: Seg
        Customer WO: SuncorWO
        Customer PO: SuncorPO
        Model: Model
        Unit: Unit
        Serial: Serial
        Title: Title
        Part Number: PartNumber
        SMR: SMR
        Date Added: DateAdded
        Date Complete: DateCompleted
        Added By: CreatedBy
        Comments: WOComments
        Comp CO: ComponentCO
        Pics: Pictures

    FC Summary:
        MineSite: MineSite
        FC Number: FCNumber
        Subject: SubjectShort
        Type: Classification
        Action Reqd: Resp
        Hrs: Hours
        Part Number: PartNumber
        Parts Avail: PartAvailability
        Comments: Comments # not sure
        Release Date: ReleaseDate
        Expiry Date: ExpiryDate
        Prog:
        Prog %:
        Hrs: Hours

    FC Details:
        UID: UID
        MineSite: MineSite
        Model: Model
        Unit: Unit
        FC Number: FCNumber
        Complete: Complete
        Sched: Scheduled
        Closed: ManualClosed
        Ignore: Ignore
        Type: Classification
        Subject: Subject
        Date Complete SMS: DateCompleteSMS
        Date Complete KA: DateCompleteKA
        Expiry Date: ExpiryDate
        SMR: SMR
        Pics: Pictures
        Notes: Notes

    TSI:
        UID: UID
        Status: StatusTSI
        Date Added: DateAdded
        TSI No: TSINumber
        WO: WorkOrder
        Model: Model
        Unit: Unit
        Serial: Serial
        Title: Title
        Unit SMR: SMR
        Part SMR: ComponentSMR
        Part Name: TSIPartName
        Part Number: PartNumber
        Serial No: SNRemoved
        Failure Cause: FailureCause
        Details: TSIDetails
        Author: TSIAuthor
        Pics: Pictures

    Component CO:
        UID: UID
        MineSite: MineSite
        Model: Model
        Unit: Unit
        Component: Component
        Side: Modifier
        Group CO: GroupCO
        CO Date: DateAdded
        Unit SMR: SMR
        Comp SMR: ComponentSMR
        SN Removed: SNRemoved
        SN Installed: SNInstalled
        Wtny: WarrantyYN
        CapUSD: CapUSD
        SMS WO: WorkOrder
        Customer WO: SuncorWO
        Customer PO: SuncorPO
        Reman: Reman
        Removal Reason: SunCOReason
        Failure Cause: FailureCause
        Status: COConfirmed
    
    Component SMR:
        MineSite: MineSite
        Model: Model
        Unit: Unit
        Component: Component
        Side: Modifier
        Bench SMR: BenchSMR
        Curr Unit SMR: CurrentUnitSMR
        SMR Last CO: SMRLastCO
        Curr Comp SMR: CurrentComponentSMR
        Pred. CO Date: PredictedCODate
        Life Remaining: LifeRemaining
        Last SN Installed: SNInstalled

    Unit Info:
        MineSite: MineSite
        Customer: Customer
        Equip Type: EquipClass
        Model: Model
        Serial: Serial
        Engine Serial: EngineSerial
        Unit: Unit
        Current SMR: CurrentSMR
        SMR Measure Date: DateSMR
        Delivery Date: DeliveryDate
        Warranty Remaining: Remaining
        GE Warranty: GE_Remaining

    Email List:
        UserGroup: UserGroup
        MineSite: MineSite
        Email: Email
        Passover: Passover
        WO Request: WORequest
        FC Cancelled: FCCancelled
        Pics DLS: PicsDLS
        PRP: PRP
        FC Summary: FCSummary
        TSI: TSI
        RAMP: RAMP
        Service: Service
        Parts: Parts
        AvailDaily: AvailDaily
        AvailReports: AvailReports
    
    Availability:
        Unit: Unit
        ShiftDate: ShiftDate
        StartDate: StartDate
        EndDate: EndDate
        Total: Duration
        SMS: SMS
        Suncor: Suncor
        Category Assigned: CategoryAssigned
        DownReason: DownReason
        Comment: Comment
        Assigned: Assigned
    
    Users:
        UserName: UserName
        Email: Email
        LastLogin: LastLogin
        Version: Ver
        Domain: Domain
        UserGroup: UserGroup
        MineSite: MineSite

    
    OilSamples:
        Silicon (Si): Si
        Sodium (Na): Na
        Potassium (K): K
        Iron (Fe): Fe
        Chromium (Cr): Cr
        Lead (Pb): Pb
        Copper (Cu): Cu
        Tin (Sn): Sn
        Aluminum (Al): Al
        Nickel (Ni): Ni
        Silver (Ag): Ag
        Titanium (Ti): Ti
        Boron (B): B
        Phosphorus (P): P
        Zinc (Zn): Zn
        Calcium (Ca): Ca
        Barium (Ba): Ba
        Magnesium (Mg): Mg
        Molybdenum (Mo): Mo
        Vanadium (V): V
        Antimony (Sb): Sb
        Lithium (Li): Li
        Beryllium (Be): Be
        Water %: water
        Grit: grit
        Visc 40°C cSt: visc40
        Visc 100°C cSt: visc100
        OPC Code: opc
        OPC > 4µ: opc_4
        OPC > 6µ: opc_6
        OPC > 14µ: opc_14
        OPC > 21µ: opc_21
        OPC > 38µ: opc_38
        OPC > 70µ: opc_70
        'Cutting #/ml': cutting
        'Sliding #/ml': sliding
        'Fatigue #/ml': fatigue
        'Non-Metal #/ml': nonMetal
        'Fibers #/ml': fibers
        Cutting Mean Size µ: cuttingMean
        Sliding Mean Size µ: slidingMean
        Fatigue Mean Size µ: fatigueMean
        Non-Metal Mean Size µ: nonMetalMean
        Visc Index: viscIndex

    FCImport:
        FC Number/Seq: FCNumber
        Distributor: Distributor
        FC Start Date: StartDate
        Model: Model
        Serial: Serial
        FC End Date: EndDate
        Subject: Subject
        Claim No: ClaimNo
        Completion SMR: SMR
        Completion Date: DateCompleteKA
        Status: Status
        SMR Limit: SMRLimit
        Classification: Classification
        FID Expiration Date: ExpiryDate
        Stock / KAC: Stock

Platform:
    mac:
        font size: 15
    win:
        font size: 11