name: Create Sentry Release

on:
    push:
        tags:
          - '*'
        # types: [published, created]

jobs:
    createSentryRelease:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2          
            - name: Sentry Release
              uses: getsentry/action-release@v1.0.1
              env:
                SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
                SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
                SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
              with:
                environment: production
                version: "3.1.6"
